from typing import List
from starstack.constants import RELION_EULER_CONVENTION, RELION_ANGLES_NAMES, RELION_SHIFTS_NAMES, \
    RELION_PRED_POSE_CONFIDENCE_NAME, RELION_ORI_POSE_CONFIDENCE_NAME, RELION_IMAGE_FNAME


BATCH_PARTICLE_ID: str = "idd"
BATCH_PARTICLES_NAME: str = "particle"
BATCH_POSE_NAME: str = "pose"
BATCH_MD_NAME: str = "md"